version: '3.8'
services:
  postgres-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'